name: ghc-9.2
on:
  - push
  - pull_request

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-latest']
        ghc: ['9.2.0.20210422']
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
    - uses: haskell/actions/setup@v1
      id: setup-haskell-cabal
      with:
        ghc-version: ${{ matrix.ghc }}
    - name: Update cabal package database
      run: cabal update
    - uses: actions/cache@v2
      name: Cache cabal stuff
      with:
        path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
        key: ${{ runner.os }}-${{ matrix.ghc }}
    # We rebuild tests several times to avoid intermittent failures on Windows
    # https://github.com/haskell/actions/issues/36
    - name: Test
      run: |
        bld() { cabal build --allow-newer='splitmix:base' pkg:text:tests; }
        bld || bld || bld
        cabal --allow-newer='splitmix:base' test
    - name: Haddock
      run: cabal --allow-newer='splitmix:base' haddock
    - name: SDist
      run: cabal sdist
    - name: Build bench
      run: cabal bench --allow-newer='splitmix:base' --benchmark-option=-l
